name: DIY-F401-Build
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install ARM Toolchain
        uses: gcc-arm-embedded/setup-arm-embedded-action@v1
        with:
          arm-gcc-version: '10-2020-q4' # Bản ổn định nhất cho F4 đời cũ

      - name: Make Firmware for F401
        run: |
          # Dùng target MATEKF411 vì nó nhẹ và khớp F401
          make TARGET=MATEKF411 EXTRA_FLAGS="-DSTM32F401xC" 
          
      - name: Upload Hex File
        uses: actions/upload-artifact@v4
        with:
          name: Betaflight-F401RC-DIY
          path: obj/*.hex
          
